### ISSUE TITLE
Eval error: ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by sjtuytc** [hjxwhy/mipnerf_pl#14]
```
Traceback (most recent call last):                                                          
  File "/data/aug_code/mipnerf_pl/eval.py", line 90, in <module>                                     
    blender_scenes = main(args)                                                                         
  File "/data/aug_code/mipnerf_pl/eval.py", line 61, in main                                                                                                            
    _, (f_rgb, distance, acc) = model(batch_rays, False, args.white_bkgd)                                                                                                     
ValueError: too many values to unpack (expected 3) 

```
The Ln62 of eval.py should be changed to:
        _, (f_rgb, distance, acc, _, _) = model(batch_rays, False, args.white_bkgd)

**Comment by ZYY-666** [comment]
Yes, this is a bug of origin code.

**Comment by hanbiao3906** [comment]
you are right，I also meet this bug

**Comment by OvOtoQAQ** [comment]
hi guys, do you solve this problem?

**Comment by csm-kr** [comment]
At eval.py 61 line (https://github.com/hjxwhy/mipnerf_pl/blob/dev/eval.py#L61), 
Try to convert the code from 
_, (f_rgb, distance, acc) = model(batch_rays, False, args.white_bkgd)
to 
f_rgb, distance, acc = model(batch_rays, False, args.white_bkgd)[-1][:3]
