### ISSUE TITLE
Value error

### ISSUE THREAD

**Issue by XiangFeng66** [hjxwhy/mipnerf_pl#15]
when I train the model , I have some problems
Validation sanity check: 0it [00:00, ?it/s]/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:110: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 128 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Traceback (most recent call last):                                                                                                                                                     
  File "train.py", line 68, in <module>
    main(parse_args(parser))
  File "train.py", line 64, in main
    trainer.fit(system, ckpt_path=hparams['checkpoint.resume_path'])
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in fit
    self._call_and_handle_interrupt(
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in run_stage
    return self._run_train()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1314, in _run_train
    self.fit_loop.run()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 140, in run
    self.on_run_start(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 197, in on_run_start
    self.trainer.reset_train_val_dataloaders(self.trainer.lightning_module)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 561, in reset_train_val_dataloaders
    self.reset_train_dataloader(model=model)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 386, in reset_train_dataloader
    raise ValueError(
ValueError: `val_check_interval` (10000) must be less than or equal to the number of the training batches (1303). If you want to disable validation set `limit_val_batches` to 0.0 instead.

what can I do to solve it

**Comment by hjxwhy** [comment]
https://github.com/hjxwhy/mipnerf_pl/blob/6c074522cd6246281391fdfdbe9e155a1f846ac2/configs/lego.yaml#L16
change this value less than 1303(which is all your training samples)
the error message has pointed out it.

**Comment by XiangFeng66** [comment]
Thanks for your answer, I got it.
