### ISSUE TITLE
Data Parse Error

### ISSUE THREAD

**Issue by ingra14m** [hjxwhy/mipnerf_pl#19]
All output after running `python train.py --out_dir . --data_path D:\Git_Project\data\nerf\nerf_synthetic\lego --dataset_name blender exp_name lego` is shown below:
```shell
Sanity Checking: 0it [00:00, ?it/s]C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 0:   0%|          | 0/20842 [00:00<?, ?it/s] Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "D:\Interesting\NeRF-Relevent\mipnerf_pl\train.py", line 68, in <module>
    main(parse_args(parser))
  File "D:\Interesting\NeRF-Relevent\mipnerf_pl\train.py", line 64, in main
    trainer.fit(system, ckpt_path=hparams['checkpoint.resume_path'])
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1112, in _run
    results = self._run_stage()
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1191, in _run_stage
    self._run_train()
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\loops\loop.py", line 194, in run
    self.on_run_start(*args, **kwargs)
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 160, in on_run_start
    _ = iter(data_fetcher)  # creates the iterator inside the fetcher
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 179, in __iter__
    self._apply_patch()
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 120, in _apply_patch
    apply_to_collections(self.loaders, self.loader_iters, (Iterator, DataLoader), _apply_patch_fn)
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 156, in loader_iters
    return self.dataloader_iter.loader_iters
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 556, in loader_iters
    self._loader_iters = self.create_loader_iters(self.loaders)
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 596, in create_loader_iters
    return apply_to_collection(loaders, Iterable, iter, wrong_dtype=(Sequence, Mapping))
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\lightning_utilities\core\apply_func.py", line 47, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
    w.start()
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\AAA\anaconda3\envs\nerf-env\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument
```

**Comment by hjxwhy** [comment]
Maybe you can checkout to master branch and try it again. I have a long time not develop this repo so I am not sure what's wrong with dev branch. I am sorry.

**Comment by ingra14m** [comment]
> Maybe you can checkout to master branch and try it again. I have a long time not develop this repo so I am not sure what's wrong with dev branch. I am sorry.
Thank you for your reply. The code has executed successfully when I switched into master branch.

**Comment by ingra14m** [comment]
> Maybe you can checkout to master branch and try it again. I have a long time not develop this repo so I am not sure what's wrong with dev branch. I am sorry.

Thank you for your reply. The code has executed successfully when I switched into master branch.
