### ISSUE TITLE
Debug problem with render_video.py:

### ISSUE THREAD

**Issue by charmingmoe** [hjxwhy/mipnerf_pl#26]
Debug problem with render_video.py:

When I try to run render_video.py on pycharm, it produces the following error:

D:\NeRF\mipnerf\mipnerf_pl-dev> python render_video.py --ckpt results/ckpt/lego/multi-epoch=35-step=298835.ckpt --out_dir video --scale 4 
Traceback (most recent call last):
  File "D:\NeRF\mipnerf\mipnerf_pl-dev\render_video.py", line 197, in <module>
    run_render(args)
  File "D:\NeRF\mipnerf\mipnerf_pl-dev\render_video.py", line 139, in run_render
    _, (f_rgb, distance, acc) = model(batch_rays, False, args.white_bkgd)
       ^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)

I have not made any changes to the code. Is there any solution, please

**Comment by Ryan2ky** [comment]
I have met the same error when I run `eval.py` and `render_video.py`. The problem is due to the fact that the second term in the output of the model is a list of 5-tuples, which we can see on the line 246 in the file `mip_nerf.py`, as following:
```python
ret.append((comp_rgb, distance, acc, weights, t_samples))
```
But, on the line 179 (`ret: list, [*(rgb, distance, acc)]`) we know it should return a list of 3-tuples, and we expected 3, too.
In order to avoid other code using this module from being affected, I **modified the code** at the calling point(**line 61** in `eval.py` and **line 139** in `render_video.py`) to the following:
```python
_, (f_rgb, distance, acc, _, _) = model(batch_rays, False, args.white_bkgd)
```
